In [10]:
with open('teste.txt', 'r') as arquivo:
        texto = [vertice for vertice in arquivo.read().split()  ] #Cria uma lista com o conteúdo presente no arquivo de teste
        vertices = int(texto[0]) #Pega o primeiro elemento da lista acima, que correnspode ao número de vértices do grafo
        arestas = [] #Lista vazia que vai conter todos os pares de arestas do grafo
        for i in range(len(texto[1:])//3):
            arestas += [[int(texto[3*i+1])]+[int(texto[3*i+2])]+ [float(texto[3*i+3])]] #Atualiza a lista de arestas, criando sublistas com os pares de arestas

print(arestas)

#arquivo_saida = open('Resultados.txt', 'a') #Cria um arquivo de saída que guardará informações sobre os grafos

[[1, 6, 2.0], [4, 8, 1.0], [2, 3, 4.0], [1, 3, 10.0], [7, 9, 3.0], [5, 10, 2.2], [10, 2, 4.3], [5, 7, 9.0], [9, 3, 5.0], [3, 5, 22.0], [1, 7, 1.5], [10, 4, 4.0]]


In [53]:
import numpy as np
import heapq
from collections import defaultdict


class Graph_l:   
    def __init__(self, v, a): #(número de vértices, arestas)
        self.aqruivo_saida = [] #Lista que vai receber os resultados desejados
        self.v = v
        self.a = a
        self.num_arestas = len(self.a) 
        self.neg = False
        self.lista = [[] for i in range(self.v)] #Não sabemos quantos elementos tem em cada linha (quantos vizinhos cada vértice tem)
        self.pesos = [[] for i in range(self.v)]  #lista que contém apenas os pesos 
        g = np.zeros(self.v,dtype=int) #Vetor de zeros, onde vamos guardar o grau de cada vértice
        for i in range(self.num_arestas):
            u=self.a[i][0] #Pega o primeiro vértice do par de arestas
            v= self.a[i][1] #Pega o segundo vértice do par de arestas
            p= self.a[i][2] #Pega o peso da aresta
            if p < 0: self.neg = True
            self.lista[u-1]+= [(v,p)] #Adiciona o vértice v na linha u (o índice é u-1, pois i se inicia no 0)
            self.lista[v-1]+= [(u, p)] #Adiciona o vértice u na linha v
            self.pesos[u-1]+= [p]
            self.pesos[v-1] += [p]
            g [u-1] += 1  #Atualiza os graus 
            g [v-1] += 1
        self.graus = g


    def mostra_lista(self): #Retorna a lista de adjacência
        return self.lista 
    
    def Dijkstra(self,vi, p):
        if self.neg == True:
            d = 'Não é possível'
            if p ==1: 
                print(f'\nDijkstra a partir de {vi} : d ')
        else:  
            pai = np.array([-1] * self.v, dtype = int) #inicia vetor com os pais
            nivel = np.array([-1] * self.v, dtype = int) #inicia vetor dos níveis
            S = np.zeros(self.v) #Definir S como vazio
            len_S = 0 #variável auxiliar para não ter que verificar a cada iteração a lista S
            dist = np.full(self.v, np.inf) #distâncias começam infinitas
            dist_aux = np.full(self.v, np.inf)
            dist_aux[vi-1]=0 
            pai [vi-1] = 0
            nivel [vi-1] = 0 
            while len_S != self.v : #Enquanto S != V
                p_u = np.min(dist_aux) #Selecione u em V-S, tal que dist[u] é mínima
                u = np.argmin(dist_aux) #u que tem a distância mínima
                if p_u == np.inf :   #grafo não é conexo
                    break
                dist[u]=dist_aux[u]
                dist_aux[u]= np.inf  #usado para que não alteremos mais a distância de quem já foi adicionado a S
                S[u]= 1 #Adicione u em S
                len_S += 1 
                for viz in range(len(self.lista[u])): #Para cada vizinho de u faça
                    v = self.lista[u][viz][0]
                    if S[v-1] ==0: 
                        if dist_aux[v-1] > dist[u] + self.lista[u][viz][1] :  #Se dist[v] > dist[u] + w(u,v) então
                            dist_aux[v-1] = dist[u] + self.lista[u][viz][1] #dist[v] = dist[u] + w(u,v)
                            pai[v-1] = u+1
                            nivel[v-1] = nivel[u] + 1
            d = [dist, pai, nivel]
            if p ==1: 
                print ('Distância sem heap: ', dist)
                #print(f'\nDijkstra a partir de {v1} : {d[0]}, árvore (pais): {d[1]}, árvore(níveis): {d[2]} ')
        return d
    
    def DijkstraHeap(self, vi,p ) :
        if self.neg == True:
            d = 'Não é possível'
            if p ==1: 
                print(f'\nDijkstra a partir de {v1} : {d} ')
        else:
            dist = np.full(self.v, np.inf) #define um vetor de custos/distancias e pais
            dist[vi-1] = 0 #define a distancia do primeiro vertice como 0 e pai vi
            h = [(0, vi)]   #pq - priority queue, adiciona o primeiro vértice no heap com distância 0
            while len(h) > 0:
                dist_atual, u =  heapq.heappop(h) #pega o último valor da fila de prioridade(maior dist)
                for vizinhos in self.lista[u-1]:
                    viz = vizinhos[0]
                    peso = vizinhos[1]
                    d = dist_atual + peso
                    if d < dist[viz-1]:
                        dist[viz-1] = d
                        heapq.heappush(h, (d, viz))
            if p==1 : 
                print ('Distância com heap: ', dist)
        return dist
    
   
    def caminho(self,v1,v2,p): #v1 é o vértice de partida, v2 o de chegada e p é para imprimir 
        pais = self.Dijkstra(v2, 0)[1]  #fazemos a árvore a partir de v2, para ir encontrando os pais de v1 até chegar em v2
        caminho = [v1] #caminho começa já com o vétice de partida
        v= v1  #começamos em v1
        if self.Dijkstra(v2, 0)[2][v1-1] == -1: 
            caminho = "Não há caminho, v2 e v1 não estão na mesma cc"
        else:
            while v != v2: #enquanto vértice analisado não for vértice destino 
                v = pais [v-1]  #próximo vértice do caminho é o pai do que último adicionado  
                caminho.append(v)   #adicionamos esse pai ao caminho
        if p==1:
            print(f'\nCaminho entre  {v1} e {v2}: {caminho} ')
        return caminho 
    
    def mostra_dj (self,vi):
        return self.Dijkstra(vi,0)
    
    def distancia(self, v1, v2, p): #Retorna a distâncoa entre dois vértices
        D= self.Dijkstra(v1, 0)[0][v2-1]
        if p ==1:
            print (D)
        return D



In [54]:
Graph_l(vertices,arestas).DijkstraHeap(1,1)

Distância com heap:  [ 0.  13.5  9.5 16.7 10.5  2.   1.5 17.7  4.5 12.7]


array([ 0. , 13.5,  9.5, 16.7, 10.5,  2. ,  1.5, 17.7,  4.5, 12.7])

In [11]:
Graph_l(vertices, arestas).mostra_lista()

[[(6, 2.0), (3, 10.0), (7, 1.5)],
 [(3, 4.0), (10, 4.3)],
 [(2, 4.0), (1, 10.0), (9, 5.0), (5, 22.0)],
 [(8, 1.0), (10, 4.0)],
 [(10, 2.2), (7, 9.0), (3, 22.0)],
 [(1, 2.0)],
 [(9, 3.0), (5, 9.0), (1, 1.5)],
 [(4, 1.0)],
 [(7, 3.0), (3, 5.0)],
 [(5, 2.2), (2, 4.3), (4, 4.0)]]

In [41]:
Graph_l(vertices, arestas).Dijkstra(1,1)



Distância sem heap:  [ 0.  13.5  9.5 16.7 10.5  2.   1.5 17.7  4.5 12.7]


[array([ 0. , 13.5,  9.5, 16.7, 10.5,  2. ,  1.5, 17.7,  4.5, 12.7]),
 array([ 0,  3,  9, 10,  7,  1,  1,  4,  7,  5]),
 array([0, 4, 3, 4, 2, 1, 1, 5, 2, 3])]

In [42]:
Graph_l(vertices, arestas).DijkstraHeap(1,1)

Distância com heap:  [ 0. inf inf inf inf inf inf inf inf inf]


array([ 0., inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [3]:
Graph_l(vertices, arestas).caminho(10,20,1)
Graph_l(vertices, arestas).caminho(10,30,1)
Graph_l(vertices, arestas).caminho(10,40,1)
Graph_l(vertices, arestas).caminho(10,50,1)
Graph_l(vertices, arestas).caminho(10,60,1)


Caminho entre  10 e 20: [10, 2038, 5094, 2875, 4746, 8892, 3578, 2502, 4627, 4252, 9853, 9285, 1034, 20] 

Caminho entre  10 e 30: [10, 2038, 2658, 682, 4045, 30] 

Caminho entre  10 e 40: [10, 2038, 2658, 682, 5941, 6759, 2195, 1223, 40] 

Caminho entre  10 e 50: [10, 2038, 7521, 2258, 3235, 8078, 2532, 2527, 50] 

Caminho entre  10 e 60: [10, 2038, 5094, 2875, 3598, 1268, 4333, 3383, 8182, 4328, 9082, 60] 


[10, 2038, 5094, 2875, 3598, 1268, 4333, 3383, 8182, 4328, 9082, 60]